### ISSUE TITLE
Unable to change name to categories

### ISSUE THREAD

**Issue by Cazaril** [FIWARE-TMForum/business-ecosystem-logic-proxy#118]
Im not really sure if this is a proxy related error but here is the full log error mensage.

2016-10-06 17:06:10.811  - FATAL: Server - c53bd0ca-c990-4ce2-ac37-a5287c3939b0 - ::ffff:127.0.0.1 - eugenio - PUT: /DSProductCatalog/api/catalogManagement/v2/category/5 - Unexpected unhandled exception - TypeError: Cannot read property 'map' of undefined. Stack trace:
TypeError: Cannot read property 'map' of undefined
    at convertCatalogData (/home/eugenio/Documentos/github/Business-API-Ecosystem/business-ecosystem-logic-proxy/lib/indexes.js:190:60)
    at Array.map (native)
    at saveIndexCatalog (/home/eugenio/Documentos/github/Business-API-Ecosystem/business-ecosystem-logic-proxy/lib/indexes.js:198:24)
    at genericSave (/home/eugenio/Documentos/github/Business-API-Ecosystem/business-ecosystem-logic-proxy/controllers/tmf-apis/catalog.js:994:13)
    at handleIndexes (/home/eugenio/Documentos/github/Business-API-Ecosystem/business-ecosystem-logic-proxy/controllers/tmf-apis/catalog.js:1008:17)
    at Object.executePostValidation (/home/eugenio/Documentos/github/Business-API-Ecosystem/business-ecosystem-logic-proxy/controllers/tmf-apis/catalog.js:1114:13)
    at Request._callback (/home/eugenio/Documentos/github/Business-API-Ecosystem/business-ecosystem-logic-proxy/controllers/tmf.js:122:41)
    at Request.self.callback (/home/eugenio/Documentos/github/Business-API-Ecosystem/business-ecosystem-logic-proxy/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/eugenio/Documentos/github/Business-API-Ecosystem/business-ecosystem-logic-proxy/node_modules/request/request.js:1048:10)
2016-10-06 17:06:10.812  - WARN: Server - c53bd0ca-c990-4ce2-ac37-a5287c3939b0 - ::ffff:127.0.0.1 - eugenio - PUT: /DSProductCatalog/api/catalogManagement/v2/category/5 - Status: 500

**Comment by fdelavega** [comment]
This issue is fixed
